### ISSUE TITLE
Cannot extract youtube player config, videoId was

### ISSUE THREAD

**Issue by SufyanQadeer** [kotvertolet/youtube-jextractor#55] opened 2020-11-30 07:52 UTC
Extraction failed. Please, report here: https://github.com/kotvertolet/youtube-jextractor/issues. Error details: Cannot extract youtube player config, videoId was: Nj2U6rhnucI

**Comment by passiatech** [comment] 2020-11-30 08:05
i have faced the same issue kindly help me too

**Comment by passiatech** [comment] 2020-11-30 08:06
> Extraction failed. Please, report here: https://github.com/kotvertolet/youtube-jextractor/issues. Error details: Cannot extract youtube player config, videoId was: Nj2U6rhnucI

how to get rid of it

**Comment by ki-erp** [comment] 2020-12-03 13:51
we are facing this error too, Please help admin.

**Comment by harinikshan** [comment] 2020-12-04 07:00
While I am testing on android 10 version devices I am getting proper videoData but while I am running on oreo level devices I am getting "Cannot extract youtube player config" exceptions.
I am using the 0.3.3 version.
please check the issue

**Comment by kotvertolet** [comment] 2020-12-04 23:40
@harinikshan @passiatech @SufyanQadeer @ki-erp U'm I'm having a hard times reproducing your issues, for me Nj2U6rhnucI works just fine. Please, provide me with additional info like what device did you used, what was the android version (api level), etc.

**Comment by harinikshan** [comment] 2020-12-05 09:50
@kotvertolet  I have added the details in below  issue list please check it. https://github.com/kotvertolet/youtube-jextractor/issues/57

**Comment by ki-erp** [comment] 2020-12-05 10:45
![WhatsApp Image 2020-12-05 at 3 47 26 PM](https://user-images.githubusercontent.com/75432395/101240343-c641b280-3714-11eb-9d5e-f796333c0024.jpeg)

The same issue occurs again, Kindly look at the attached file.

**Comment by SufyanQadeer** [comment] 2020-12-05 18:06
> @harinikshan @passiatech @SufyanQadeer @ki-erp Guys, I'm having a hard times reproducing your issues, for me **Nj2U6rhnucI** works just fine. Please, provide me with additional info like what device did you used, what was the android version (api level), etc.

Hi Brother, yes this issue is fixed automatically.

**Comment by harinikshan** [comment] 2020-12-05 18:32
@SufyanQadeer how this issue is fixed automatically?

**Comment by ki-erp** [comment] 2020-12-06 15:44
@SufyanQadeer, what to do if your application is live on play store and using this API, no issue is resolved automatically, Admin please do needful, Thanks in Advanced.

**Comment by kotvertolet** [comment] 2020-12-06 18:57
@ki-erp  Firstly, I do not recommend you put an application with this library into the playstore because your app and you will be both banned, this library violates Google user agreement, they do not let you to play youtube videos in a background or to play only audio, it is strongly prohibited. Please, be advised.

**Comment by ki-erp** [comment] 2020-12-08 11:28
> @ki-erp Firstly, I do not recommend you to put an application with this library into the play store because your app and you will be both banned, this library violates Google user agreement, they do not let you to play youtube videos in the background or to play only audio, it is strongly prohibited. Please, be advised.

Thank you for the advice admin, But we are playing our own youtube videos still it's prohibited.

**Comment by niteshfel** [comment] 2020-12-24 05:03
any update on this

**Comment by antonyhaman** [comment] 2021-03-22 18:52
@niteshfel should be fixed now

**Closed by antonyhaman** 2021-03-22 18:52 UTC
Labels: needs investigation

**Comment by ghost** [comment] 2022-04-30 12:08
Is there any progress with issue or not yet ?
